name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t containers08 .

      - name: Create container
        run: docker create --name container --volume database:/var/www/db containers08

      - name: Copy tests into container
        run: docker cp ./tests container:/var/www/html

      - name: Start container
        run: docker start container

      - name: Run tests
        run: docker exec container php /var/www/html/tests/tests.php

      - name: Stop container
        run: docker stop container

      - name: Remove container
        run: docker rm container

      - name: Remove Docker image
        run: docker rmi containers08 || true
